baseURL = "https://pbedn.github.io/"
languageCode = "en-us"
title = "Coding Notes"
author = "Pawel Bednarz"
tags = ["blog", "python", "programming"]
features = ["blog", "python", "programming"]
# Shown in the side menu
copyright = "&#169; 2021 Pawel Bednarz"
canonifyurls = true
paginate = 10
disableKinds=["RSS"]
enableRobotsTXT = true

DefaultContentLanguage = "en"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  brand = "PBedn"
  googleAnalytics = "UA-74192356-1"
  # disqus = "pbedn"
  # CSS name for highlight.js
  highlightjs = "github"

  dateFormat = "02 Jan 2006"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  # custom_css = ["css/my.css"]
  # custom_js = ["js/my.js"]

[social]
  linkedin = "pbedn"
  github = "pbedn"
#  stackoverflow = "4877932"

[Languages]
[Languages.en]
weight = 1

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Blogroll"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 3
    identifier = "links"
    url = "/links/"
  [[menu.main]]
    name = "Books"
    pre = "<i class='fa fa-question fa-fw'></i>"
    weight = 4
    identifier = "books"
    url = "/books/"

# [Languages.pl]
# title = "Notatki programisty"
# weight = 2
# [[Languages.pl.menu.main]]
#   name = "Główna"
#   pre = "<i class='fa fa-home fa-fw'></i>"
#   weight = 1
#   identifier = "home"
#   url = "/pl/"
